# .rubocop.yml
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-performance   # （任意）

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "frontend/**/*" # モノレポなら

# Request/Feature系はテストが長くなりがちなので“最短で通す”設定
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - "spec/requests/**/*"

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - "spec/requests/**/*"
