apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never          
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend.dev.svc.cluster.local:3000
          ports:
            - containerPort: 3000
