name: CI

on:
  push:
  pull_request:

jobs:
  rails:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app_test
      # 外部連携はダミーで潰す
      SENDGRID_API_KEY: test
      JWT_SECRET_KEY: test
      # master.key を使っている場合のみ設定
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install native deps
        run: sudo apt-get update -y && sudo apt-get install -y libpq-dev

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: DB prepare
        run: bin/rails db:prepare

      - name: Lint (Rubocop)
        run: bundle exec rubocop -P || true

      - name: RSpec
        run: bundle exec rspec --format progress
